### ISSUE TITLE
Cant use this plugin to write unit tests.

### ISSUE THREAD

**Issue by djmittens** [groovy/groovy-android-gradle-plugin#43] opened 2015-03-16 20:07 UTC
I was interested in using this plugin to unit test code however it does not seem to work at all.

I followed instructions here to set up the project
http://tools.android.com/tech-docs/unit-testing-support

However i can only get java unit tests working.

**Comment by pieces029** [comment] 2015-03-16 20:10
Could you elaborate on your issue? I have regular android unit tests (JUnit3) as well as spock tests running. 

Are you using the snapshot? I was having issues with that.

**Comment by djmittens** [comment] 2015-03-16 20:12
I used the instructions from the README file and i was using the latest stable, or at least so i thought, even AS wasnt marking the directory as test, and it was completely ignored by  `gradle test` command.

**Comment by pieces029** [comment] 2015-03-16 20:18
Just to confirm you are using the 0.3.5 version of this plugin? What version of the Android Gradle Plugin are you using? 0.3.5 is only compatible with Android Gradle Plugin 1.0.0.

The tests should be placed in androidTest directory (you can change this in the gradle file if you want). To run the tests use `./gradlew connectedAndroidTest` or `./gradlew cAT` for short.

**Comment by djmittens** [comment] 2015-03-16 20:21
im using this for the gradle android plugin
```
        classpath 'com.android.tools.build:gradle:1.1.3'
```

and yes im using 0.3.5 as described in the instructions of the readme

**Comment by pieces029** [comment] 2015-03-16 20:23
Change the number to 1.0.0 on the android gradle plugin.

**Comment by djmittens** [comment] 2015-03-16 20:24
gave me an error in android studio saying gradle dsl method not found 'testCompile()'

**Comment by pieces029** [comment] 2015-03-16 20:27
That doesn't really provide any information that I could use to help you.

Could you share your build.gradle?

**Comment by djmittens** [comment] 2015-03-16 20:28
Maybe we are talking about 2 different kinds of tests, the testAndroid directory has to do with tests running on the device correct?

Im using the new functionality to compile jvm tests as specified in the link ive provided, which means my tests would live under `src/test/groovy | java`

**Comment by pieces029** [comment] 2015-03-16 20:51
For that you will need to use the Snapshot version of this plugin and the latest version of the Android Gradle plugin.

**Comment by andresviedma** [comment] 2015-03-16 22:37
@djmittens today's changes should allow you to do that. You'll also need Android gradle plugin 1.1.0+.

**Comment by melix** [comment] 2015-03-17 13:47
If someone can confirm that the issue is fixed with 0.3.6-SNAPSHOT I will release a new version. Thanks!

**Comment by morgotth** [comment] 2015-04-01 23:33
I confirm that 0.3.6-SNAPSHOT is working with last android plugin (1.1.3).
My test project: https://github.com/morgotth/AndroidJavaAlternatives

**Comment by jaredsburrows** [comment] 2015-04-10 02:37
@morgotth  Thank you for posting this! I will be able to close my current issue out(https://github.com/groovy/groovy-android-gradle-plugin/issues/44) after @melix makes the release.

What is the ETA on the release?

**Comment by melix** [comment] 2015-04-10 08:40
The release is out for several weeks now, sorry you didn't notice.

**Closed by melix** 2015-04-10 08:40 UTC
