### ISSUE TITLE
Plugin + Jack/Java8

### ISSUE THREAD

**Issue by X4fyr** [groovy/groovy-android-gradle-plugin#135] opened 2016-10-19 18:22 UTC
Hey,

actually the plugins fails to run with Jack enabled.
I get the following error with plugin and Jack enabled:
`Error:Cannot cast object 'task ':app:transformJackWithJackForDebug'' with class'com.android.build.gradle.internal.pipeline.TransformTask_Decorated' to class 'org.gradle.api.tasks.SourceTask'`

This might be related to #113

**Comment by pieces029** [comment] 2016-10-19 19:33
Closing as a duplicate of #113

**Closed by pieces029** 2016-10-19 19:33 UTC
