### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [groovy/groovy-android-gradle-plugin#79] opened 2016-01-18 19:31 UTC
This error appears when I try to build the project. Here's the project-level `build.gradle` file:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.7'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

And this is the app `build.gradle` file:
```
apply plugin: 'com.android.application'
apply plugin: 'groovyx.grooid.groovy-android'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.my.package.name"
        minSdkVersion 9
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
        men {
            applicationId "com.my.firstappid"
            versionName "1.0-men"
        }
        women {
            applicationId "com.my.secondappid"
            versionName "1.0-women"
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'org.codehaus.groovy:groovy:2.4.5:grooid'
}
```

Moving the `apply plugin: 'groovyx.grooid.groovy-android'` line between the two files doesn't help.
I'm on OS X/Android Studio 1.5.1.
Java version:
```
$ javac -version
javac 1.7.0_79
```

**Comment by pieces029** [comment] 2016-01-19 14:22
Could you please include the error in its entirety?

**Comment by github-account-because-they-want-it** [comment] 2016-01-19 14:27
OK. Here it goes:
`Error:(2, 0) Cause: groovyx/grooid/GroovyAndroidPlugin : Unsupported major.minor version 52.0`

**Comment by amritbhandari** [comment] 2016-01-20 18:17
I get the exact same error. I am on Windows 10, IntelliJ 15.0.1, jdk 8

**Comment by mariogarcia** [comment] 2016-01-24 19:40
@pieces029 That usually happens when the library (or plugin) has been compiled and distributed using jdk 8 without having jdk7 compatibility in mind. I would make sure that the plugin source compatibility and target compatibility points at 1.6/1.7

**Comment by amritbhandari** [comment] 2016-01-25 08:47
Still no luck. I made sure my IntelliJ project's sdk was JDK7.
I did brief look at the plugins used and they all seem to be on JDK7

Heres my build.gradle files content 
```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.7' // Android/Groovy
        classpath 'net.kaleidos.gradle.plugins:emerger:0.0.2' // Emerger
        classpath 'com.google.gms:google-services:1.5.0'
    }
}
allprojects {
    repositories {
        jcenter()
    }
}
task wrapper(type: Wrapper) {
    gradleVersion = '2.9'
}

-------------------------------------------------------------------------------------
apply plugin: 'com.android.application'
apply plugin: 'groovyx.grooid.groovy-android'
apply plugin: 'net.kaleidos.gradle.plugins.emerger'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.*.*"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 0
        versionName "0.1"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
project.androidGroovy {
    options {
        configure(groovyOptions) {
            encoding = 'UTF-8'
            forkOptions.jvmArgs = ['-noverify'] // maybe necessary if you use Google Play Services
        }
        sourceCompatibility = '1.7'
        targetCompatibility = '1.7'
    }
}
repositories {
    mavenCentral()
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'org.codehaus.groovy:groovy:2.4.5:grooid'
    compile 'com.facebook.android:facebook-android-sdk:4.8.2'
    compile 'com.google.android.gms:play-services-identity:8.3.0'
    compile 'com.google.android.gms:play-services-plus:8.3.0'
    compile "com.arasthel:swissknife:1.4.0"
    compile 'com.scottyab:secure-preferences-lib:0.1.4'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    compile 'com.pkmmte.view:circularimageview:1.1'
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'
}
```

using version 0.3.7 for classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:***' causes 
```
Error:(1, 0) Gradle: A problem occurred evaluating project ':app'.
> java.lang.UnsupportedClassVersionError: groovyx/grooid/GroovyAndroidPlugin : Unsupported major.minor version 52.0
```

using version 0.3.6 I get
```
Error:Gradle: Execution failed for task ':app:compileDebugGroovyWithGroovyc'.
> No such property: bootClasspath for class: com.android.builder.core.AndroidBuilder
```

**Comment by mariogarcia** [comment] 2016-01-25 12:52
@amritbhandari Just to clarify: I was talking about the plugin (version 0.3.7), not about your project. At the moment I'm using the following versions for a project I'm working on:

    classpath 'com.android.tools.build:gradle:1.3.1'
    classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.6'

First dependency is a workaround to the `Unsupported...` issue, and the second solves `No such property: bootClasspath` issue.

I hope version 0.3.8 will solve the `Unsupported...` issue in order to go back to latest android tools.

**Comment by boylenssen** [comment] 2016-01-28 11:50
I worked around it by using a snapshot:

`buildscript {
    repositories {
        jcenter()
        maven {
            url = 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'org.codehaus.groovy:gradle-groovy-android-plugin:0.3.8-SNAPSHOT'
    }
}`

source: https://github.com/groovy/groovy-android-gradle-plugin

**Comment by pieces029** [comment] 2016-01-28 20:24
@boylenssen were you having this issue with `0.3.7`?  I don't think I changed anything in terms of how the plugin worked from that release.

**Comment by boylenssen** [comment] 2016-01-29 10:03
@pieces029 yes, I had the exact same error message as above (and so did a co-worker, on a different project). Using the snapshot solved the issue

**Comment by pieces029** [comment] 2016-01-29 16:48
Not sure what would have changed between the two. Do you happen to have a project I could look at? I'll do a release as soon as I get the latest pieces completed, and close this ticket out.

**Comment by boylenssen** [comment] 2016-02-01 08:31
@pieces029 here, I pushed something here :) https://github.com/boylenssen/groovyissue

This is with the snapshot. Just change to 0.3.7 in https://github.com/boylenssen/groovyissue/blob/master/build.gradle to get this issue

**Comment by pieces029** [comment] 2016-02-01 14:28
@boylenssen Great thanks. I'll take a look when I get a chance.

**Comment by pieces029** [comment] 2016-02-01 15:06
@mariogarcia for `0.3.7` release the compile version was set to 1.6, like all the previous builds. https://github.com/groovy/groovy-android-gradle-plugin/blob/69eea7249646a05da52018ea4a43a06baab2dbb6/gradle/compile.gradle

And in `0.3.8-SNAPSHOT` I have the version set directly in the module's gradle. https://github.com/groovy/groovy-android-gradle-plugin/blob/master/gradle-groovy-android-plugin/gradle-plugin.gradle

@boylenssen The project you have provided for me works fine, but I am also using Java 8.

So, even though the build was to `1.6` something must have been messed up. If I could get a few more people to confirm `0.3.8-SNAPSHOT` fixes the issue, I would gladly put out another release.

I'll see if I can downgrade my Java version to also confirm the fix.

**Comment by amritbhandari** [comment] 2016-02-01 16:43
@pieces029 I can confirm that when I moved to using gradle-groovy-android-plugin:0.3.8-SNAPSHOT I stopped getting the "java.lang.UnsupportedClassVersionError: groovyx/grooid/GroovyAndroidPlugin : Unsupported major.minor version 52.0"

**But**, this is when things get a bit more interesting. When I tried to replicate the error on the codebase given by @boylenssen, I just couldnot get it to reproduce the error.
It turns out that if I use JDK8 for compilation there are no issues. But when I use JDK7 I get the error.

So in my system JDK7 + 0.3.7 causes the error. JDK7 + 0.3.8-SNAPSHOT works.
With JDK8 everything works.

In my IntelliJ project the java sdk was set to JDK7 for the project, and thats why i was getting the errors.
But from my command line my JAVA_HOME was set to JDK8 and I just didnt get the error.

See if you can replicate the behaviour I am getting.

**Comment by pieces029** [comment] 2016-02-02 15:25
I have released `0.3.8` which was compiled with Java 6 as the Java Version, so all projects using Java 6+ should no longer see this error message.

**Closed by pieces029** 2016-02-02 15:25 UTC

**Comment by boylenssen** [comment] 2016-02-04 07:29
I can confirm that this fixes it

**Comment by ViliusKraujutis** [comment] 2016-11-06 19:12
If you have same issue on Jenkins, update Java version at **Jenkins->Manage Jenkins->Global Tool Configuration->JDK**.

**Comment by KalicyZhou** [comment] 2017-05-03 08:40
org.gradle.java.home=/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home
